#!/usr/bin/env bash
#
# Builds Resources/mons/dex_entries.txt -- the text the Pokedex detail view's
# second page shows -- from PokeAPI (https://pokeapi.co).
#
# Resources/mons/ is gitignored on purpose. Pokedex entries are Nintendo /
# Game Freak's writing: fine to fetch onto your own device, not fine to commit
# or redistribute. Same rule as the sprites. See README "Pokedex entries".
#
#   Scripts/fetch_dex_entries.sh              # all 151, in English
#   Scripts/fetch_dex_entries.sh --lang es    # in Spanish
#   Scripts/fetch_dex_entries.sh 1 4 7        # just these three
#
# A species with no line here shows "NO DEX ENTRY" rather than a broken
# screen, so fetching a subset is a supported state.
#
# The file is one entry per line, `<dex number>|<text>`; `#` comments and
# blank lines are ignored. It holds one language at a time, because the app
# reads a single dex_entries.txt -- re-run with a different --lang to switch.

set -euo pipefail

cd "$(dirname "$0")/.."

DST="Resources/mons"
OUT="$DST/dex_entries.txt"
API="https://pokeapi.co/api/v2/pokemon-species"
lang="en"

if ! command -v python3 >/dev/null 2>&1; then
  echo "error: python3 is required (it parses the JSON)" >&2
  exit 1
fi

if [ "${1-}" = "--lang" ]; then
  lang="${2-}"
  if [ -z "$lang" ]; then
    echo "error: --lang needs a code, e.g. en es fr de it ja" >&2
    exit 2
  fi
  shift 2
fi

if [ $# -eq 0 ]; then
  set -- $(seq 1 151)
fi

mkdir -p "$DST"

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
  echo "# Pokedex entries from PokeAPI (https://pokeapi.co), language: $lang"
  echo "# (c) Nintendo / Game Freak / The Pokemon Company -- not redistributable."
  echo "# Generated by Scripts/fetch_dex_entries.sh; do not commit this file."
} > "$tmp"

missing=0
for dex in "$@"; do
  # PokeAPI asks for considerate use and this is 151 sequential calls, so the
  # loop stays serial with a short pause rather than firing them all at once.
  json="$(curl -fsSL --retry 3 --retry-delay 2 "$API/$dex/" 2>/dev/null || true)"
  if [ -z "$json" ]; then
    echo "  !  #$dex: fetch failed, skipping" >&2
    missing=$((missing + 1))
    sleep 0.2
    continue
  fi

  line="$(LANG_CODE="$lang" DEX="$dex" python3 - "$json" <<'PY' || true
import json, os, re, sys
data = json.loads(sys.argv[1])
want = os.environ["LANG_CODE"]
texts = [e for e in data.get("flavor_text_entries", [])
         if e.get("language", {}).get("name") == want]
if not texts:
    sys.exit(1)
# Prefer the most recent version's wording; the list is oldest-first.
raw = texts[-1].get("flavor_text", "")
# PokeAPI keeps the games' own line breaks, form feeds and soft hyphens.
text = raw.replace("­\n", "").replace("­", "")
text = re.sub(r"[\n\f\r]+", " ", text)
text = re.sub(r"\s+", " ", text).strip()
# The renderer draws one monospaced face, so keep it to plain ASCII-ish
# punctuation rather than the typographic quotes some entries carry.
text = text.replace("’", "'").replace("‘", "'")
text = text.replace("“", '"').replace("”", '"')
text = text.replace("–", "-").replace("—", "-")
if not text:
    sys.exit(1)
print(f'{int(os.environ["DEX"])}|{text}')
PY
)"

  if [ -z "$line" ]; then
    echo "  !  #$dex: no '$lang' entry, skipping" >&2
    missing=$((missing + 1))
  else
    echo "$line" >> "$tmp"
    printf '  .  #%s\n' "$dex"
  fi
  sleep 0.2
done

mv "$tmp" "$OUT"
trap - EXIT

count="$(grep -cv '^#' "$OUT" || true)"
echo
echo "wrote $OUT ($count entries, language: $lang)"
if [ "$missing" -gt 0 ]; then
  echo "$missing species had no entry and were skipped -- they show NO DEX ENTRY."
fi
echo "Rebuild to bundle it, or copy it into Files -> On My iPhone -> iTamaPoke/mons/."
